version: '3.0'
services:
  ##POSTGRESQL
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: app